FROM node:20-slim AS frontend-build
WORKDIR /app/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM python:3.11-slim
WORKDIR /app

COPY pyproject.toml ./
COPY src/ ./src/
RUN pip install --no-cache-dir -e .

# Ships with real trained models immediately instead of needing a full
# historical fetch+train before the first prediction can be served -- same
# reasoning as F1_Predictor's/PL_Predictor's own Dockerfiles, and required
# here specifically because PUBLIC_MODE=true below blocks the in-band
# retrain endpoint (routes.py's _admin_only-equivalent gate), so a
# freshly-deployed container with no models baked in has no way at all to
# produce one. .gitignore excludes models/*.pkl and models/*.json from git
# (they're regenerated by training, not hand-written), but that has no
# bearing on this COPY -- it reads straight from the local build context.
COPY models/manifest.json models/game_outcome_model.pkl models/anytime_td_model.pkl \
     models/passing_yards_model.pkl models/receiving_yards_model.pkl \
     models/rushing_yards_model.pkl models/total_points_model.pkl ./models/

COPY --from=frontend-build /app/frontend/dist ./frontend/dist

ENV PYTHONPATH=/app/src
ENV PUBLIC_MODE=true

EXPOSE 8003
CMD ["sh", "-c", "uvicorn cfb_predictor.api.main:app --host 0.0.0.0 --port ${PORT:-8003}"]
