"""config.py — paths, env loading, and shared constants."""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
CACHE_DIR = DATA_DIR / "cache"
MODELS_DIR = PROJECT_ROOT / "models"
FRONTEND_DIST_DIR = PROJECT_ROOT / "frontend" / "dist"

PUBLIC_MODE = os.getenv("PUBLIC_MODE", "false").lower() == "true"

GAMES_CACHE_DIR = CACHE_DIR / "games"
TEAMS_CACHE_DIR = CACHE_DIR / "teams"
PLAYER_STATS_CACHE_DIR = CACHE_DIR / "player_stats"
ODDS_CACHE_DIR = CACHE_DIR / "odds"
ROSTER_CACHE_DIR = CACHE_DIR / "rosters"

CURRENT_SEASON = 2026  # bump each new CFB season (typically August)

# CollegeFootballData.com — this project's nfl_data_py equivalent, free but
# API-keyed and rate-capped at 1,000 calls/month on the free tier. Request a
# key once at collegefootballdata.com/key.
CFBD_API_KEY = os.getenv("CFBD_API_KEY")

ODDS_API_KEY = os.getenv("ODDS_API_KEY")
ODDS_API_SPORT_KEY = "americanfootball_ncaaf"
ODDS_API_BASE_URL = "https://api.the-odds-api.com/v4/sports"

# RapidAPI's Sportsbook API (data/sportsbook_api.py) -- the live-odds
# pipeline's primary source since 2026-09, same switch PL_Predictor made
# and for the same reason: The Odds API's shared key (used across several
# of this account's projects) confirmed live at 500/500 credits used, 0
# remaining. This key comes from a completely separate provider/quota
# (150 requests/day, one request per event -- no bulk/batch odds endpoint
# exists). CFB has far more games per week than NFL/PL, so caching is
# load-bearing here, not just a latency optimization -- see
# SPORTSBOOK_CACHE_TTL_SECONDS.
SPORTSBOOK_API_KEY = os.getenv("SPORTSBOOK_API_KEY")
SPORTSBOOK_API_HOST = "sportsbook-api2.p.rapidapi.com"
SPORTSBOOK_API_BASE_URL = f"https://{SPORTSBOOK_API_HOST}/v0"
SPORTSBOOK_NCAAF_COMPETITION_KEY = "ei8e-xitw-a3B6"  # ncaa-football, from GET /v0/competitions
SPORTSBOOK_CACHE_DIR = CACHE_DIR / "sportsbook"
# Must stay well above refresh-public-snapshot.yml's own cron interval (4h).
# A TTL shorter than the cron gap (the old 2h value) guarantees every single
# scheduled run finds a stale cache and re-fetches all ~65 current-week
# events from scratch -- confirmed live: that alone burns the shared
# 150/day cap before the day's other runs (or other projects sharing this
# key, e.g. PL_Predictor's own much more frequent but much better-cached
# polling) get anything, leaving spreads permanently null. 20h means only
# the day's first run actually spends quota; every later run that same day
# reuses it.
SPORTSBOOK_CACHE_TTL_SECONDS = 20 * 3600

TRACKING_DB_PATH = DATA_DIR / "tracking.db"

# SQLite doesn't work reliably over Azure Files/SMB (confirmed live:
# "database is locked" the moment TRACKING_DB_PATH itself was pointed at
# the mounted cache volume) -- so the live database still lives on local,
# ephemeral container disk, wiped on every cold start (this app scales to
# zero between requests). CACHE_DIR is the one directory that IS on a
# persistent Azure Files mount (see the Container App's volume config).
# api/main.py copies the live db here right after every tracking tick,
# and restores from here at startup -- a plain file copy at a quiescent
# point (no open connection at either end) sidesteps SQLite's own
# locking model entirely, unlike trying to query the db directly over
# the network share.
TRACKING_DB_BACKUP_PATH = CACHE_DIR / "tracking_backup.db"

# Precomputed games/predictions/player-props for a window of weeks, so the
# public deployment never runs this project's live feature-building
# pipeline (CFBD game/player-stat fetch, feature build, model predict) on
# an actual request -- especially not the CFBD calls, which are what
# exhausted the 1,000-calls/month quota in the first place. Generated by
# `python -m cfb_predictor.public_snapshot` and committed like any other
# tracked file; the copy baked into the image is only the cold-start
# fallback -- a running process stays current by polling
# PUBLIC_SNAPSHOT_REFRESH_URL on a timer (api/routes.py::
# refresh_public_snapshot_from_remote, polled from api/main.py's lifespan)
# instead of waiting for a redeploy.
PUBLIC_SNAPSHOT_PATH = DATA_DIR / "public_snapshot.json"
PUBLIC_SNAPSHOT_REFRESH_URL = os.getenv(
    "PUBLIC_SNAPSHOT_REFRESH_URL",
    "https://raw.githubusercontent.com/Kevocado/CFB_Predictor/main/data/public_snapshot.json",
)
PUBLIC_SNAPSHOT_POLL_SECONDS = int(os.getenv("PUBLIC_SNAPSHOT_POLL_SECONDS", "300"))

for _d in (
    DATA_DIR,
    CACHE_DIR,
    MODELS_DIR,
    GAMES_CACHE_DIR,
    TEAMS_CACHE_DIR,
    PLAYER_STATS_CACHE_DIR,
    ODDS_CACHE_DIR,
    ROSTER_CACHE_DIR,
    SPORTSBOOK_CACHE_DIR,
):
    _d.mkdir(parents=True, exist_ok=True)
